/**
 * Configuration Descriptions
 * Format: "path.to.key": "Description text".
 */
export const configDescriptions = {

    // CHEAT CONFIG - Top Level
    "cheatConfig.unban": "Prevents accounts from being banned. May not work due to multiple ban methods",
    "cheatConfig.ingameUI": "Enables the in-game UI overlay",
    "cheatConfig.steamachieve": "Allows unlocking Steam achievements",
    "cheatConfig.chng_enabled": "⚠ DANGER: If true, 'chng' command becomes available. ONLY enable if you know what you are doing!",

    // MAXVAL - Resource Caps
    "cheatConfig.maxval.bones": "Maximum limit for bones to prevent save corruption",
    "cheatConfig.maxval.totalbones": "Maximum limit for total bones across all characters",
    "cheatConfig.maxval.dust": "Maximum limit for dust to prevent save corruption",
    "cheatConfig.maxval.totaldust": "Maximum limit for total dust across all characters",
    "cheatConfig.maxval.tach": "Maximum limit for tachyon to prevent save corruption",
    "cheatConfig.maxval.totaltach": "Maximum limit for total tachyon across all characters",
    "cheatConfig.maxval.creditcap": "Maximum credit capacity for dungeons",
    "cheatConfig.maxval.flurbocap": "Maximum flurbo capacity for dungeons",

    // GODLIKE
    "cheatConfig.godlike.respawn": "Mob respawn time (lower is faster)",

    // UNLOCK
    "cheatConfig.unlock.islands": "String of IDs for islands to unlock (e.g., 'abcde_')",

    "cheatConfig.multiply.printer": "Multiplies sample print by x, overrides lab/god bonus",
    "cheatConfig.multiply.carrycap": "Carry capacity multiplier",
    "cheatConfig.multiply.damage": "Total damage multiplier",
    "cheatConfig.multiply.money": "Money drops multiplier",
    "cheatConfig.multiply.drop": "Drop rarity multiplier",
    "cheatConfig.multiply.afk": "AFK gains multiplier",
    "cheatConfig.multiply.skillexp": "Skill XP gain multiplier",
    "cheatConfig.multiply.classexp": "Class XP gain multiplier",
    "cheatConfig.multiply.efficiency": "Skilling efficiency multiplier",
    "cheatConfig.multiply.crystal": "Crystal spawn chance multiplier",
    "cheatConfig.multiply.shopstock": "Shop stock quantity multiplier",

    // WIDE - Miscellaneous Wide Cheats
    "cheatConfig.wide.autoloot.itemstochest": "Automatically sends looted items to the chest",
    "cheatConfig.wide.autoloot.moneytochest": "Automatically sends looted money to the chest",
    "cheatConfig.wide.autoloot.zenithfarm": "Zenith farming drops are excluded from autoloot and drop normally",
    "cheatConfig.wide.autoloot.materialfarm": "Monster material drops are excluded from autoloot and drop normally",
    "cheatConfig.wide.autoloot.hidenotifications": "Hides loot and money notifications",
    "cheatConfig.wide.perfectobols.preferredstat": "The stats that should be rolled when using perfectobols (e.g., PRIMARY, STR)",
    "cheatConfig.wide.plunderous.allcharacters": "Enables plunderous mob bonuses for all characters",
    "cheatConfig.wide.arcade.ArcadeCost": "Arcade Shop costs. (lower is better)",
    "cheatConfig.wide.dartshop.DartsUpgCost": "Dart Shop upgrade costs. (lower is better)",
    "cheatConfig.wide.hoopshop.HoopsUpgCost": "Hoop Shop upgrade costs. (lower is better)",

    // WIPE
    "cheatConfig.wipe.cogs": "Wipes all cogs currently on the board",

    // W1 - World 1
    "cheatConfig.w1.anvil.productionspeed": "Anvil: Item production speed",
    "cheatConfig.w1.forge.speed": "Forge: Bar processing speed",
    "cheatConfig.w1.forge.capacity": "Forge: Ore capacity",
    "cheatConfig.w1.stampcost": "Stamps: Upgrade costs. (lower is better)",
    "cheatConfig.w1.companion.companions": "Comma-separated list of companion IDs to enable (e.g., '0,1,2'). Leave empty for all",
    "cheatConfig.w1.companion.current": "Active companion ID (e.g., '11' for Glunko)",
    "cheatConfig.w1.owl.OwlCost": "Owl: Upgrade costs. (lower is better)",
    "cheatConfig.w1.owl.OwlFeatherRate": "Owl: Feather gain rate",
    "cheatConfig.w1.owl.OwlBonuses": "Owl: All owl-related bonuses",
    "cheatConfig.w1.owl.OwlFeatherShinyGe": "Owl: Shiny feather generation (unknown effect)",

    // W2 - World 2
    "cheatConfig.w2.roo.RooCost": "Roo: Upgrade costs. (lower is better)",
    "cheatConfig.w2.roo.RooShinyMulti": "Roo: Shiny catch rates",
    "cheatConfig.w2.roo.RooCatchRate": "Roo: Standard catch rates",
    "cheatConfig.w2.roo.RooCatchREQ": "Roo: Catch requirements. (lower is better)",
    "cheatConfig.w2.roo.RooCatchFishQTY": "Roo: Quantity of fish caught",
    "cheatConfig.w2.roo.RooCatchRate_S": "Roo: Shiny catch rates",
    "cheatConfig.w2.roo.RooCatchREQ_S": "Roo: Shiny catch requirements. (lower is better)",
    "cheatConfig.w2.roo.RooCatchRate_T": "Roo: Tar pit catch rates",
    "cheatConfig.w2.roo.RooCatchREQ_T": "Roo: Tar pit catch requirements. (lower is better)",

    // Alchemy
    "cheatConfig.w2.alchemy.BubbleBonus": "Alchemy: All bubble effects",
    "cheatConfig.w2.alchemy.CauldronCosts": "Alchemy: Bubble upgrade costs",
    "cheatConfig.w2.alchemy.ResearchSpeed": "Alchemy: Brewing speed",
    "cheatConfig.w2.alchemy.VialCosts": "Alchemy: Vial costs. (lower is better)",
    "cheatConfig.w2.alchemy.VialBonus": "Alchemy: Vial effects",
    "cheatConfig.w2.alchemy.PctChanceNewBubble": "Alchemy: New bubble discovery chance",
    "cheatConfig.w2.alchemy.CauldronLvsBrewREQ": "Alchemy: Cauldron level requirements. (lower is better)",
    "cheatConfig.w2.alchemy.LiquidCap": "Alchemy: Liquid storage capacity",
    "cheatConfig.w2.alchemy.LiquidHRrate": "Alchemy: Liquid generation speed",
    "cheatConfig.w2.alchemy.sigilspeed": "Alchemy: Sigil research speed",

    // W3 - World 3
    "cheatConfig.w3.buildspd": "Construction: Building speed",
    "cheatConfig.w3.WorshipSpeed": "Worship: Charge generation speed",
    "cheatConfig.w3.towerdamage": "Tower Defense: Tower damage",
    "cheatConfig.w3.refineryspeed": "Refinery: Cycle speed. Don't go below 1! (lower is better)",
    "cheatConfig.w3.trapping": "Trapping: Trap timer speed",

    // W4 - World 4
    "cheatConfig.w4.fasteggs": "Breeding: Egg incubation speed. (lower is better)",
    "cheatConfig.w4.petchance": "Breeding: New pet discovery chance",
    "cheatConfig.w4.petupgrades": "Breeding: Pet upgrade costs. (lower is better)",
    "cheatConfig.w4.mealspeed": "Cooking: Meal preparation speed. (lower is better)",
    "cheatConfig.w4.recipespeed": "Cooking: Recipe research speed. (lower is better)",
    "cheatConfig.w4.kitchensdiscount": "Cooking: Kitchen and spice costs. (lower is better)",
    "cheatConfig.w4.platesdiscount": "Cooking: Plate upgrade costs. (lower is better)",
    "cheatConfig.w4.fastforaging": "Cooking: Foraging speed",
    "cheatConfig.w4.luckychef": "Cooking: New recipe discovery luck",

    // Superpets
    "cheatConfig.w4.superpets.BlockChance": "Pet Arena: Block chance when attacked",
    "cheatConfig.w4.superpets.TotalDMG": "Pet Arena: Total pet damage",

    // Mainframe
    "cheatConfig.w4.mainframe.0": "Mainframe: Animal farm damage bonus percentage",
    "cheatConfig.w4.mainframe.1": "Mainframe: Wired In printer multiplier",
    "cheatConfig.w4.mainframe.2": "Mainframe: Refinery cycle speed multiplier",
    "cheatConfig.w4.mainframe.3": "Mainframe: Alchemy bubble level gain (affects multi-bubble discovery)",
    "cheatConfig.w4.mainframe.4": "Mainframe: Deathnote and portal kill multiplier",
    "cheatConfig.w4.mainframe.5": "Mainframe: Enable Shrine World Tour effect",
    "cheatConfig.w4.mainframe.6": "Mainframe: Alchemy liquid capacity multiplier",
    "cheatConfig.w4.mainframe.7": "Mainframe: Stamp bonus multiplier (must be 2 to work)",
    "cheatConfig.w4.mainframe.8": "Mainframe: Spelunker jewel effect multiplier",
    "cheatConfig.w4.mainframe.9": "Mainframe: Fungi Finger Pocketer cash bonus multiplier",
    "cheatConfig.w4.mainframe.10": "Mainframe: Alchemy vial bonus multiplier",
    "cheatConfig.w4.mainframe.11": "Mainframe: Banking Fury damage multiplier",
    "cheatConfig.w4.mainframe.12": "Mainframe: Enable sigils in alchemy",
    "cheatConfig.w4.mainframe.13": "Mainframe: Lab connection range multiplier",
    "cheatConfig.w4.mainframe.100": "Mainframe: Meal cooking speed multiplier",
    "cheatConfig.w4.mainframe.101": "Mainframe: Additional animal farm damage % per pet",
    "cheatConfig.w4.mainframe.102": "Mainframe: Lab XP gain bonus percentage",
    "cheatConfig.w4.mainframe.103": "Mainframe: Trim all building slots bonus",
    "cheatConfig.w4.mainframe.104": "Mainframe: All Stat bonus percentage",
    "cheatConfig.w4.mainframe.105": "Mainframe: Breeding XP gain bonus percentage",
    "cheatConfig.w4.mainframe.106": "Mainframe: Kitchen level up per day bonus",
    "cheatConfig.w4.mainframe.107": "Mainframe: Adds to bonus 3 (multi-bubble discovery)",
    "cheatConfig.w4.mainframe.108": "Mainframe: Food non-consume chance percentage",
    "cheatConfig.w4.mainframe.109": "Mainframe: Connection range for bonuses and jewels",
    "cheatConfig.w4.mainframe.110": "Mainframe: Extra damage bonus percentage",
    "cheatConfig.w4.mainframe.111": "Mainframe: Reduced egg incubation time percentage",
    "cheatConfig.w4.mainframe.112": "Mainframe: Base efficiency bonus for all skills",
    "cheatConfig.w4.mainframe.113": "Mainframe: Fungi Finger Pocketer extra cash percentage",
    "cheatConfig.w4.mainframe.114": "Mainframe: Meal cooking bonus speed percentage",
    "cheatConfig.w4.mainframe.115": "Mainframe: Pet passive ability speed percentage",
    "cheatConfig.w4.mainframe.116": "Mainframe: Additional meal bonus percentage",
    "cheatConfig.w4.mainframe.117": "Mainframe: Damage per greened stack bonus",

    // Chipbonuses
    "cheatConfig.w4.chipbonuses.resp": "Lab Chip: Mob respawn speed bonus percentage",
    "cheatConfig.w4.chipbonuses.card1": "Lab Chip: Double top-left card effect (1 = yes)",
    "cheatConfig.w4.chipbonuses.card2": "Lab Chip: Double bottom-right card effect (1 = yes)",
    "cheatConfig.w4.chipbonuses.crys": "Lab Chip: Crystal spawn chance on kill percentage",
    "cheatConfig.w4.chipbonuses.star": "Lab Chip: Double star sign effects (1 = yes)",
    "cheatConfig.w4.chipbonuses.mkill": "Lab Chip: Multikill per tier bonus percentage",
    "cheatConfig.w4.chipbonuses.linewidth": "Lab Chip: Lab line width bonus percentage",
    "cheatConfig.w4.chipbonuses.dmg": "Lab Chip: Damage bonus percentage",
    "cheatConfig.w4.chipbonuses.move": "Lab Chip: Movement speed bonus percentage",
    "cheatConfig.w4.chipbonuses.acc": "Lab Chip: Accuracy bonus percentage",
    "cheatConfig.w4.chipbonuses.pend": "Lab Chip: Double pendant bonuses (1 = yes)",
    "cheatConfig.w4.chipbonuses.key1": "Lab Chip: Double first keychain bonuses (1 = yes)",
    "cheatConfig.w4.chipbonuses.troph": "Lab Chip: Double trophy bonuses (1 = yes)",
    "cheatConfig.w4.chipbonuses.def": "Lab Chip: Defense bonus percentage",
    "cheatConfig.w4.chipbonuses.weappow": "Lab Chip: Weapon power bonus percentage",
    "cheatConfig.w4.chipbonuses.dr": "Lab Chip: Drop rarity bonus percentage",
    "cheatConfig.w4.chipbonuses.toteff": "Lab Chip: Skilling efficiency bonus percentage",
    "cheatConfig.w4.chipbonuses.eff": "Lab Chip: Base skilling efficiency bonus",
    "cheatConfig.w4.chipbonuses.labexp": "Lab Chip: Lab XP bonus percentage",
    "cheatConfig.w4.chipbonuses.atkspd": "Lab Chip: Attack speed bonus percentage",
    "cheatConfig.w4.chipbonuses.safk": "Lab Chip: Skill AFK gains bonus percentage",
    "cheatConfig.w4.chipbonuses.fafk": "Lab Chip: Fight AFK gains bonus percentage",

    // Meals
    "cheatConfig.w4.meals.TotDmg": "",
    "cheatConfig.w4.meals.Mcook": "",
    "cheatConfig.w4.meals.Cash": "",
    "cheatConfig.w4.meals.Rcook": "",
    "cheatConfig.w4.meals.Npet": "",
    "cheatConfig.w4.meals.BrExp": "",
    "cheatConfig.w4.meals.Seff": "",
    "cheatConfig.w4.meals.VIP": "",
    "cheatConfig.w4.meals.Lexp": "",
    "cheatConfig.w4.meals.Def": "",
    "cheatConfig.w4.meals.PxLine": "",
    "cheatConfig.w4.meals.KitchenEff": "",
    "cheatConfig.w4.meals.TimeEgg": "",
    "cheatConfig.w4.meals.KitchC": "",
    "cheatConfig.w4.meals.PetDmg": "",
    "cheatConfig.w4.meals.TDpts": "",
    "cheatConfig.w4.meals.CookExp": "",
    "cheatConfig.w4.meals.Breed": "",
    "cheatConfig.w4.meals.TotAcc": "",
    "cheatConfig.w4.meals.AtkSpd": "",
    "cheatConfig.w4.meals.Sprow": "",
    "cheatConfig.w4.meals.Lib": "",
    "cheatConfig.w4.meals.Critter": "",
    "cheatConfig.w4.meals.Crit": "",
    "cheatConfig.w4.meals.LinePct": "",
    "cheatConfig.w4.meals.TPpete": "",
    "cheatConfig.w4.meals.Liquid12": "",
    "cheatConfig.w4.meals.DivExp": "",
    "cheatConfig.w4.meals.GamingBits": "",
    "cheatConfig.w4.meals.Liquid34": "",
    "cheatConfig.w4.meals.Sailing": "",
    "cheatConfig.w4.meals.GamingExp": "",

    // W5 - World 5
    // Sailing
    "cheatConfig.w5.sailing.IslandDistance": "Sailing: Island distance (lower is closer)",
    "cheatConfig.w5.sailing.MaxChests": "Sailing: Maximum chest limit (Warning: too high may break cloud saves)",
    "cheatConfig.w5.sailing.RareTreasureChance": "Sailing: Rare treasure find chance",
    "cheatConfig.w5.sailing.Minimumtraveltime": "Sailing: Minimum travel time in minutes. (lower is better)",
    "cheatConfig.w5.sailing.BoatUpgCostType": "Sailing: Loot type ID for boat upgrades",
    "cheatConfig.w5.sailing.BoatUpgCostQty": "Sailing: Loot quantity for upgrades. (lower is better)",
    "cheatConfig.w5.sailing.BoatValue": "Sailing: Loot quantity gained from boats",
    "cheatConfig.w5.sailing.BoatSpeed": "Sailing: Boat travel speed",
    "cheatConfig.w5.sailing.CloudDiscoverBonus": "Sailing: Cloud discovery bonuses",
    "cheatConfig.w5.sailing.ArtifactRarity": "Sailing: Artifact discovery chance. (lower is better)",
    "cheatConfig.w5.sailing.AncientChances": "Sailing: Ancient artifact chance. (lower is better)",
    "cheatConfig.w5.sailing.EldritchChances": "Sailing: Eldritch artifact chance. (lower is better)",
    "cheatConfig.w5.sailing.SovereignChances": "Sailing: Sovereign artifact chance. (lower is better)",
    "cheatConfig.w5.sailing.OmnipotentChances": "Sailing: Omnipotent artifact chance. (lower is better)",
    "cheatConfig.w5.sailing.NewCaptBoatSlot": "Sailing: Cost for unlocking new boat and captain slots. (lower is better)",
    "cheatConfig.w5.sailing.BuyCaptainCost": "Sailing: Cost for hiring new captains. (lower is better)",
    "cheatConfig.w5.sailing.ArtifactBonus": "Sailing: All artifact-provided bonuses",

    // Gaming
    "cheatConfig.w5.gaming.FertilizerUpgCosts": "Gaming: Fertilizer upgrade costs. (lower is better)",
    "cheatConfig.w5.gaming.SproutCapacity": "Gaming: Max sprout slots",
    "cheatConfig.w5.gaming.MutateUpgCosts": "Gaming: Mutation upgrade costs. (lower is better)",
    "cheatConfig.w5.gaming.LogBookBitBonus": "Gaming: Bit bonuses from the logbook",
    "cheatConfig.w5.gaming.GamingExpPCT": "Gaming: Gaming XP gain percentage",
    "cheatConfig.w5.gaming.NewMutantChanceDEC": "Gaming: Decimal new mutant chance (1 = guaranteed)",
    "cheatConfig.w5.gaming.SproutGrowthCHANCEperMUT": "Gaming: Growth chance per mutation",
    "cheatConfig.w5.gaming.SproutGrowthTime": "Gaming: Sprout growth speed. (lower is better)",
    "cheatConfig.w5.gaming.SaveSprinkler": "Gaming: Chance to save water when using sprinkler",
    "cheatConfig.w5.gaming.ImportItemCOST": "Gaming: Import item costs. (lower is better)",
    "cheatConfig.w5.gaming.AcornShopCost": "Gaming: Acorn shop upgrade costs. (lower is better)",
    "cheatConfig.w5.gaming.BoxCost": "Gaming: New box costs. (lower is better)",
    "cheatConfig.w5.gaming.SnailStuff": "Gaming: Snail logic (0: upgrade chance, 1: reset chance, 2: bit multi)",
    "cheatConfig.w5.gaming.SnailMail": "Gaming: Enable/disable Snail Mail automation",
    "cheatConfig.w5.gaming.PaletteLuck": "Gaming: Palette-related luck",
    "cheatConfig.w5.gaming.PaletteBonus": "Gaming: Palette-related bonuses",

    // Divinity
    "cheatConfig.w5.divinity.unlinks": "Divinity: Allows unlinking gods at any time",
    "cheatConfig.w5.divinity.StyleLvReq": "Divinity: Meditation style level requirements. (lower is better)",
    "cheatConfig.w5.divinity.DivPerHr": "Divinity: Base divinity points gained per hour",
    "cheatConfig.w5.divinity.DivPerHr_EXP": "Divinity: Base divinity XP gained per hour",
    "cheatConfig.w5.divinity.BlesssBonus": "Divinity: God blessing bonuses",
    "cheatConfig.w5.divinity.Bonus_MAJOR": "Divinity: Major god bonuses",
    "cheatConfig.w5.divinity.Bonus_Minor": "Divinity: Minor god bonuses",
    "cheatConfig.w5.divinity.OfferingCost": "Divinity: Offering costs. (lower is better)",
    "cheatConfig.w5.divinity.OfferingOdds": "Divinity: Success probability for offerings",

    // Collider
    "cheatConfig.w5.collider.AtomsUnlocked": "Collider: Number of unlocked atoms (max 10)",
    "cheatConfig.w5.collider.AtomCost": "Collider: Atom collider upgrade costs. (lower is better)",
    "cheatConfig.w5.collider.AtomBonuses": "Collider: Bonuses provided by atoms",
    "cheatConfig.w5.collider.AtomBubbleUpgCost": "Collider: Atom bubble upgrade costs. (lower is better)",

    // Holes
    "cheatConfig.w5.holes.VillagerExpPerHour": "Sneaking: Villager XP gain speed",
    "cheatConfig.w5.holes.BuildCost": "Sneaking: Building upgrade costs. (lower is better)",
    "cheatConfig.w5.holes.BucketFillRate": "Sneaking: Bucket fill speed",
    "cheatConfig.w5.holes.AmpMulti": "Sneaking: Amplifier effects",
    "cheatConfig.w5.holes.MeasurementCost": "Sneaking: Measurement upgrade costs. (lower is better)",
    "cheatConfig.w5.holes.MeasurementBaseBonus": "Sneaking: Measurement base bonuses",
    "cheatConfig.w5.holes.MotherlodeEffBase": "Sneaking: Base efficiency for the motherlode. (lower is better)",
    "cheatConfig.w5.holes.MonumentRewardMulti": "Sneaking: Monument rewards",
    "cheatConfig.w5.holes.MonumentROGbonuses": "Sneaking: Right-side monument rewards",
    "cheatConfig.w5.holes.Bravery_MinDMG": "Bravery: Minimum bravery damage",
    "cheatConfig.w5.holes.Bravery_MaxDMG": "Bravery: Maximum bravery damage",
    "cheatConfig.w5.holes.Bravery_SwordsOwned": "Bravery: Number of swords owned",
    "cheatConfig.w5.holes.MaxRerolls": "Bravery: Max rerolls allowed",
    "cheatConfig.w5.holes.MaxRevisions": "Bravery: Max revisions allowed",
    "cheatConfig.w5.holes.Bravery_MonsterHP": "Bravery: Monster HP. (lower is better)",
    "cheatConfig.w5.holes.Bravery_BlueChestChanceDEC": "Bravery: Probability of blue chest spawn. (lower is better)",
    "cheatConfig.w5.holes.BellCosts": "Sneaking: Bell improvement costs. (lower is better)",
    "cheatConfig.w5.holes.BellBonuss": "Sneaking: Bell bonuses",
    "cheatConfig.w5.holes.BellExpPerHR": "Sneaking: Bell XP gain speed",
    "cheatConfig.w5.holes.BellEXPreq": "Sneaking: Bell XP requirements. (lower is better)",
    "cheatConfig.w5.holes.HarpNewNote_Cost": "Sneaking: New harp note costs. (lower is better)",
    "cheatConfig.w5.holes.HarpNoteProduced": "Sneaking: Harp note production",
    "cheatConfig.w5.holes.HarpPOWperHR": "Sneaking: Harp power gain speed",
    "cheatConfig.w5.holes.LampWishCost": "Sneaking: Lamp wish costs. (lower is better)",
    "cheatConfig.w5.holes.LampWishPerDay": "Sneaking: Daily lamp wish limit",
    "cheatConfig.w5.holes.MushKillsLeft": "Sneaking: Remaining mushroom kills required for boss. (lower is better)",
    "cheatConfig.w5.holes.J_StartCoins": "Justice: Starting coins",
    "cheatConfig.w5.holes.J_Happiness": "Justice: Starting happiness",
    "cheatConfig.w5.holes.J_Dismissals": "Justice: Starting dismissals",
    "cheatConfig.w5.holes.J_StartHealth": "Justice: Starting health",
    "cheatConfig.w5.holes.Justice_BlueChestChanceDEC": "Justice: Probability of blue chest spawn. (lower is better)",
    "cheatConfig.w5.holes.BolaiaStudyRate": "Sneaking: Bolaia study speed",
    "cheatConfig.w5.holes.JarProductionPerHR": "Sneaking: Jar production speed",
    "cheatConfig.w5.holes.TempleTorchCost": "Sneaking: Temple torch costs. (lower is better)",
    "cheatConfig.w5.holes.JarCollectibleBonus": "Sneaking: Jar collectible bonuses",
    "cheatConfig.w5.holes.JarEnchantChance": "Sneaking: Jar enchantment success chance",
    "cheatConfig.w5.holes.JarNewCollectibleChance": "Sneaking: New jar collectible discovery chance",
    "cheatConfig.w5.holes.Cost_FountainUPG": "Fountain: Upgrade costs. (lower is better)",
    "cheatConfig.w5.holes.Fount_RoyalChance": "Fountain: Royal stack chance",
    "cheatConfig.w5.holes.Fount_RoyalMulti": "Fountain: Royal stack value multiplier",
    "cheatConfig.w5.holes.Fount_MarblePerFill": "Fountain: Marble gained per Yellow Water fill",
    "cheatConfig.w5.holes.Fount_MarbleizeCost": "Fountain: Upgrade marbleization costs. (lower is better)",

    // W6 - World 6
    // Farming
    "cheatConfig.w6.farming.GrowthReq": "Farming: Plant growth time. (lower is better)",
    "cheatConfig.w6.farming.OGunlocked": "Farming: Overgrowth shop unlock state (0 = locked, 1 = unlocked)",
    "cheatConfig.w6.farming.NextOGchance": "Farming: Next overgrowth discovery chance",
    "cheatConfig.w6.farming.OGmulti": "Farming: Overgrowth bonuses",
    "cheatConfig.w6.farming.PlotOwned": "Farming: Number of plots owned (max 36)",
    "cheatConfig.w6.farming.MarketCostType": "Farming: Plant type ID for market upgrades",
    "cheatConfig.w6.farming.MarketCostQTY": "Farming: Plant quantity for upgrades. (lower is better)",
    "cheatConfig.w6.farming.NextCropChance": "Farming: Next plant evolution discovery chance",
    "cheatConfig.w6.farming.CropsBonusValue": "Farming: Crop value/bonus",
    "cheatConfig.w6.farming.CropsOnVine": "Farming: Crops per plant",
    "cheatConfig.w6.farming.GrowthRate": "Farming: Base growth rate multiplier",
    "cheatConfig.w6.farming.ExoticPurchasesAllowed": "Farming: Allowed exotic purchases (max 8)",
    "cheatConfig.w6.farming.ExoticLVQTY": "Farming: Exotic level quantities",

    // Ninja
    "cheatConfig.w6.ninja.EmporiumCost": "Ninja: Emporium upgrade costs. (lower is better)",
    "cheatConfig.w6.ninja.KOtime": "Ninja: Knockout duration. (lower is better)",
    "cheatConfig.w6.ninja.ActionSpd": "Ninja: Action speed",
    "cheatConfig.w6.ninja.Stealth": "Ninja: Stealth rating",
    "cheatConfig.w6.ninja.DetectionDEC": "Ninja: Detection rate. (lower is better)",
    "cheatConfig.w6.ninja.DoorMaxHP": "Ninja: Door max HP",
    "cheatConfig.w6.ninja.JadeUpgCost": "Ninja: Jade upgrade costs. (lower is better)",
    "cheatConfig.w6.ninja.ItemStat": "Ninja: Item stats",
    "cheatConfig.w6.ninja.ItemFindOdds": "Ninja: Item find chance",
    "cheatConfig.w6.ninja.PristineBon": "Ninja: Pristine Charm bonuses",

    // Summoning
    "cheatConfig.w6.summoning.ManaStart": "Summoning: Starting mana in battles",
    "cheatConfig.w6.summoning.ManaRegen": "Summoning: Mana regeneration speed",
    "cheatConfig.w6.summoning.UnitSpd": "Summoning: Ally unit movement speed",
    "cheatConfig.w6.summoning.UnitHP": "Summoning: Ally unit HP",
    "cheatConfig.w6.summoning.UnitDMG": "Summoning: Ally unit damage",
    "cheatConfig.w6.summoning.UnitDODGE": "Summoning: Ally unit dodge probability (max 1)",
    "cheatConfig.w6.summoning.EndlessUnlocked": "Summoning: Unlocks endless mode (1 = yes)",
    "cheatConfig.w6.summoning.SummUpgBonus": "Summoning: Summoning upgrade bonuses",
    "cheatConfig.w6.summoning.SummRockEssGen": "Summoning: Essence generation rate",
    "cheatConfig.w6.summoning.UpgCost": "Summoning: Upgrade costs (0 = free). (lower is better)",
    "cheatConfig.w6.summoning.UnitCost": "Summoning: Unit summoning costs. (lower is better)",
    "cheatConfig.w6.summoning.RerollCost": "Summoning: Reroll costs (0 = free). (lower is better)",
    "cheatConfig.w6.summoning.SummEXPgain": "Summoning: Summoning XP gain",
    "cheatConfig.w6.summoning.EnemyHP": "Summoning: Enemy unit HP. (lower is better)",
    "cheatConfig.w6.summoning.EnemyDMG": "Summoning: Enemy unit damage. (lower is better)",
    "cheatConfig.w6.summoning.EnemySpd": "Summoning: Enemy unit movement speed",

    // Grimoire
    "cheatConfig.w6.grimoire.GrimoireBoneQTYbase": "Grimoire: Bone quantity base value",
    "cheatConfig.w6.grimoire.GrimoireUpgCost": "Grimoire: Upgrade costs. (lower is better)",
    "cheatConfig.w6.grimoire.Grimoire_HP": "Grimoire: HP",
    "cheatConfig.w6.grimoire.Grimoire_DMG": "Grimoire: Damage",
    "cheatConfig.w6.grimoire.Grimoire_ACC": "Grimoire: Accuracy",
    "cheatConfig.w6.grimoire.Grimoire_DEF": "Grimoire: Defense",
    "cheatConfig.w6.grimoire.Grimoire_CRITPCT": "Grimoire: Crit Chance",
    "cheatConfig.w6.grimoire.Grimoire_CRITDMG": "Grimoire: Crit Damage",

    // Windwalker
    "cheatConfig.w6.windwalker.CompassUpgCost": "Windwalker: Compass upgrade costs. (lower is better)",
    "cheatConfig.w6.windwalker.Compass_HP": "Windwalker: HP",
    "cheatConfig.w6.windwalker.Compass_DMG": "Windwalker: Damage",
    "cheatConfig.w6.windwalker.Compass_ACC": "Windwalker: Accuracy",
    "cheatConfig.w6.windwalker.Compass_DEF": "Windwalker: Defense",
    "cheatConfig.w6.windwalker.Compass_CRITPCT": "Windwalker: Crit Chance",
    "cheatConfig.w6.windwalker.Compass_CRITDMG": "Windwalker: Crit Damage",
    "cheatConfig.w6.windwalker.Compass_MoveSpeed": "Windwalker: Movement speed bonus",
    "cheatConfig.w6.windwalker.TempestMultishotPCT": "Windwalker: Tempest multishot chance",
    "cheatConfig.w6.windwalker.CompassDustQTYbase": "Windwalker: Dust quantity base value",
    "cheatConfig.w6.windwalker.TempestWepDropChance": "Windwalker: Probability of Tempest weapon drops",
    "cheatConfig.w6.windwalker.TempestRingDropChance": "Windwalker: Probability of Tempest ring drops",
    "cheatConfig.w6.windwalker.TempestStoneDropChance": "Windwalker: Probability of Tempest stone drops",
    "cheatConfig.w6.windwalker.TempestMedallionDropChance": "Windwalker: Probability of Tempest medallion drops",
    "cheatConfig.w6.windwalker.PortalCostQTY": "Windwalker: Items required for portal access. (lower is better)",

    // Arcane
    "cheatConfig.w6.arcane.ArcaneUpgCost": "Arcane: Arcane upgrade costs. (lower is better)",
    "cheatConfig.w6.arcane.Arcane_HP": "Arcane: HP",
    "cheatConfig.w6.arcane.Arcane_DMG": "Arcane: Damage",
    "cheatConfig.w6.arcane.Arcane_ACC": "Arcane: Accuracy",
    "cheatConfig.w6.arcane.Arcane_DEF": "Arcane: Defense",
    "cheatConfig.w6.arcane.Arcane_CRITPCT": "Arcane: Crit Chance",
    "cheatConfig.w6.arcane.Arcane_CRITDMG": "Arcane: Crit Damage",
    "cheatConfig.w6.arcane.Arcane_AttackSpdPCT": "Arcane: Attack Speed",
    "cheatConfig.w6.arcane.ArcaneMultishotPCT": "Arcane: Arcane multishot chance",
    "cheatConfig.w6.arcane.TenteyeclePCT": "Arcane: Tenteyecle proc chance",
    "cheatConfig.w6.arcane.PrismaBubDropChance": "Arcane: Probability of Prisma Bubble drops",
    "cheatConfig.w6.arcane.WepDropChance": "Arcane: Probability of weapon drops",
    "cheatConfig.w6.arcane.RingDropChance": "Arcane: Probability of ring drops",
    "cheatConfig.w6.arcane.DoubleItemDropz": "Arcane: Probability of double item drops",
    "cheatConfig.w6.arcane.ExtraTachyon": "Arcane: Extra tachyon gain",
    "cheatConfig.w6.arcane.ExtraTachyonMulti": "Arcane: Extra tachyon bonuses",
    "cheatConfig.w6.arcane.ArcaneTachyonQTYbase": "Arcane: Tachyon quantity base value",
    "cheatConfig.w6.arcane.ArcaneMobSpawnQTY": "Arcane: Mobs spawned by Arcane Crystal ability",
    "cheatConfig.w6.arcane.CrystalChargeReq": "Arcane: Kill requirement to spawn Arcane mobs. (lower is better)",
    "cheatConfig.w6.arcane.TimeLeft": "Arcane: Remaining time for the Arcane Barrier encounter",

    // Sneak Symbol
    "cheatConfig.w6.sneaksymbol.SneakSymbolChanceBase": "Sneaking: Base chance for Sneak Symbol procs",

    // W7 - World 7
    // Bubba
    "cheatConfig.w7.bubba.MeatsliceRate": "Bubba: Meat slicing speed",
    "cheatConfig.w7.bubba.UpgCost": "Bubba: Upgrade costs. (lower is better)",
    "cheatConfig.w7.bubba.DoubleLVchancePCT": "Bubba: Double level chance on upgrade",
    "cheatConfig.w7.bubba.DailyPetting": "Bubba: Daily petting limit",
    "cheatConfig.w7.bubba.DailyPet_HappinessQTY": "Bubba: Happiness gained from petting",
    "cheatConfig.w7.bubba.DailyPet_HappinessFromUpg": "Bubba: Happiness gained from upgrades",
    "cheatConfig.w7.bubba.HappinessLoss": "Bubba: Happiness decay rate. (lower is better)",
    "cheatConfig.w7.bubba.CharismaTraitSPD": "Bubba: Charisma trait speed",
    "cheatConfig.w7.bubba.CharismaTraitREQ": "Bubba: Charisma trait requirements. (lower is better)",
    "cheatConfig.w7.bubba.CharismaBonus": "Bubba: Charisma bonuses",
    "cheatConfig.w7.bubba.GiftPassiveBonus": "Bubba: Gift-provided passive bonuses",
    "cheatConfig.w7.bubba.Dice_Result": "Bubba: Modifier for dice roll results",
    "cheatConfig.w7.bubba.SmokeMeat_Multi": "Bubba: Smoked Meat gain",
    "cheatConfig.w7.bubba.SpareCoins_Multi": "Bubba: Spare Coins gain",

    // Spelunk
    "cheatConfig.w7.spelunk.POW": "Spelunking: Spelunking power",
    "cheatConfig.w7.spelunk.StaminaMax": "Spelunking: Maximum stamina",
    "cheatConfig.w7.spelunk.StaminaRegenRate": "Spelunking: Stamina regeneration speed",
    "cheatConfig.w7.spelunk.OverstimFillRate": "Spelunking: Overstim fill speed",
    "cheatConfig.w7.spelunk.AmberGain": "Spelunking: Amber gain",
    "cheatConfig.w7.spelunk.AmberDropChance": "Spelunking: Probability of primary amber drops",
    "cheatConfig.w7.spelunk.AmberDropChance2nd": "Spelunking: Probability of secondary amber drops",
    "cheatConfig.w7.spelunk.EscapeRopeChance": "Spelunking: Escape rope find chance",
    "cheatConfig.w7.spelunk.TollExitTax": "Spelunking: Toll exit tax. (lower is better)",
    "cheatConfig.w7.spelunk.SpelunkingEfficiency": "Spelunking: Spelunking efficiency",
    "cheatConfig.w7.spelunk.SpelunkingSpeed": "Spelunking: Spelunking speed. (lower is better)",
    "cheatConfig.w7.spelunk.ExaltDropChance": "Spelunking: Probability of exalt drops",
    "cheatConfig.w7.spelunk.PrismaDropChance": "Spelunking: Probability of prisma drops",
    "cheatConfig.w7.spelunk.MiscDropChance": "Spelunking: Probability of miscellaneous item drops",
    "cheatConfig.w7.spelunk.GoldPieceDropChance": "Spelunking: Probability of gold piece drops",
    "cheatConfig.w7.spelunk.w7itemDropChance": "Spelunking: Probability of World 7 item drops",
    "cheatConfig.w7.spelunk.blingbagDropChance": "Spelunking: Probability of bling bag drops",
    "cheatConfig.w7.spelunk.ShadowStrikeChance": "Spelunking: Probability of Shadow Strike procs",
    "cheatConfig.w7.spelunk.GrandDiscoveries_FindChance": "Spelunking: Grand Discovery find chance",
    "cheatConfig.w7.spelunk.RockPOWreq": "Spelunking: Rock power requirements. (lower is better)",
    "cheatConfig.w7.spelunk.RockHP": "Spelunking: Rock HP. (lower is better)",
    "cheatConfig.w7.spelunk.StaminaCostMulti": "Spelunking: Stamina costs. (lower is better)",

    // Gallery
    "cheatConfig.w7.gallery.GalleryBonusMulti": "Gallery: All gallery-provided bonuses",
    "cheatConfig.w7.gallery.InitializeTrophyBonuses": "Gallery: Logic for initializing trophy bonuses",
    "cheatConfig.w7.gallery.InitializeNametagBonuses": "Gallery: Logic for initializing nametag bonuses",
    "cheatConfig.w7.gallery.PodiumsOwned_Lv4": "Gallery: Level 4 podiums owned (max 19)",

    // Sushi
    "cheatConfig.w7.sushi.UpgLvREQ": "Sushi: Upgrade level requirements. (lower is better)",
    "cheatConfig.w7.sushi.UpgCost": "Sushi: Upgrade costs. (lower is better)",
    "cheatConfig.w7.sushi.FuelCost": "Sushi: Sushi fuel costs. (lower is better)",
    "cheatConfig.w7.sushi.FuelGen": "Sushi: Fuel generation rate",
    "cheatConfig.w7.sushi.FuelCap": "Sushi: Maximum fuel capacity",
    "cheatConfig.w7.sushi.CurrencyperHR": "Sushi: Money generation per hour",
    "cheatConfig.w7.sushi.KnowledgeXP_req": "Sushi: Knowledge XP requirements per level. (lower is better)",
    "cheatConfig.w7.sushi.KnowledgeXP_multi": "Sushi: Knowledge XP gain multiplier",

    // Reef
    "cheatConfig.w7.reef.ReefCost": "Reef: Costs. (lower is better)",

    // Clam
    "cheatConfig.w7.clam.ClamPromochance": "Clams: Probability of clam promotion",
    "cheatConfig.w7.clam.ClamBonuses": "Clams: Clam-provided bonuses",
    "cheatConfig.w7.clam.ClamPearlValue": "Clams: Pearl value",
    "cheatConfig.w7.clam.Clam_BlackPearlValue": "Clams: Black pearl value",
    "cheatConfig.w7.clam.Clam_Cost": "Clams: Clam costs. (lower is better)",
    "cheatConfig.w7.clam.Clam_PearlUpgReq": "Clams: Pearl upgrade requirements. (lower is better)",
    "cheatConfig.w7.clam.Clam_Mobs": "Clams: Mob spawns",

    // Coral Kid
    "cheatConfig.w7.coralkid.CoralKidUpgCost": "Coral Kid: Upgrade costs. (lower is better)",

    // Big Fish
    "cheatConfig.w7.bigfish.BigFishCost": "Big Fish: Costs. (lower is better)",

    // Zenith
    "cheatConfig.w7.zenith.ZenithMarketCost": "Zenith: Market upgrade costs. (lower is better)",
    "cheatConfig.w7.zenith.ZenithMarketBonus": "Zenith: Market-provided bonuses",
    "cheatConfig.w7.spelunkdepth": "Spelunking: Current depth (one-shot, resets to 0 after use)",
    "cheatConfig.w7.spelunkmana.StaminaCostMulti": "Spelunking: No stamina cost in spelunking",

    // Minehead
    "cheatConfig.w7.minehead.UpgCost": "Minehead: Upgrade costs. (lower is better)",
    "cheatConfig.w7.minehead.DailyTries": "Minehead: Daily tries",
    "cheatConfig.w7.minehead.MaxHP_You": "Minehead: Max HP",
    "cheatConfig.w7.minehead.BaseDMG": "Minehead: Base damage",
    "cheatConfig.w7.minehead.CurrentOutgoingDMG": "Minehead: Outgoing damage",
    "cheatConfig.w7.minehead.CurrencyGain": "Minehead: Currency gain",
    "cheatConfig.w7.minehead.BluecrownOdds": "Minehead: Blue crown odds",
    "cheatConfig.w7.minehead.JackpotOdds": "Minehead: Jackpot odds",
    "cheatConfig.w7.minehead.JackpotTiles": "Minehead: Jackpot tiles",
    "cheatConfig.w7.minehead.InstaRevealsTotal": "Minehead: Total insta reveals",

    // Glimbo
    "cheatConfig.w7.glimbo.Glimbo_Cost": "Glimbo: Glimbo cost. (lower is better)",
    "cheatConfig.w7.glimbo.GlimboDRmulti": "Glimbo: Drop rate multiplier",

    // Research
    "cheatConfig.w7.research.AFKgainsRatePCT": "Research: AFK gains rate",
    "cheatConfig.w7.research.MaxRoll": "Research: Max roll",
    "cheatConfig.w7.research.RollsPerDay": "Research: Rolls per day",
    "cheatConfig.w7.research.MagnifiersOwned": "Research: Magnifiers owned",
    "cheatConfig.w7.research.ResearchEXPrateObj": "Research: EXP rate object",
    "cheatConfig.w7.research.ObservationInsightExpRate": "Research: Insight EXP rate",
    "cheatConfig.w7.research.Kalei_MultiBase": "Research: Kaleidoscope base multi",
    "cheatConfig.w7.research.TinyCogsPerDay": "Research: Tiny cogs per day",
    "cheatConfig.w7.research.MSA_BonusRewards": "Research: MSA bonus rewards",
    "cheatConfig.w7.research.SmallCogBonus": "Research: Small cog bonuses",
    "cheatConfig.w7.research.SmallCogBonusTOTAL": "Research: Total small cog bonuses",

    // INJECTOR CONFIG
    "injectorConfig.logLevel": "Log verbosity level: debug, info, warn, or error",
    "injectorConfig.injreg": "Regex pattern used to find the injection point in the game code",
    "injectorConfig.interceptPattern": "Script filename pattern to intercept (N.js)",
    "injectorConfig.enableUI": "Enable/disable the webui",
    "injectorConfig.onLinuxTimeout": "Timeout in milliseconds for Linux-specific operations",
    "injectorConfig.webPort": "Port for the webui",
    "injectorConfig.target": "Injection target platform (steam or web)",
    "injectorConfig.webUrl": "Idleon web URL when using browser injection",
    "injectorConfig.browserPath": "Browser executable path for web injection (auto if empty)",
    "injectorConfig.browserUserDataDir": "Browser user data dir for web injection (optional)"
};
